ALTER TABLE department ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE room ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE program ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE semester ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE student_profile ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE lecturer_profile ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
